name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      # Setup node.js and yarn
      - name: 'Setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Setup Expo 
      - name: 'Setup Expo'
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}

      # Install npm dependencies
      - name: 'Install dependencies'
        run: yarn install

      # Publish
      - name: 'Publish'
        run: yarn build:android