name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      # Setup node.js and yarn
      - name: '🏗 Setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn

      # Setup Expo 
      - name: '🏗 Setup Expo and EAS'
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install npm dependencies
      - name: '📦 Install dependencies'
        run: yarn install

      # Build
      - name: '🚀 Build app (android)'
        run: yarn build:android:production