name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      # Setup node.js and yarn
      - name: 'Setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Install npm dependencies
      - name: 'Install dependencies'
        run: yarn install

      # Eslint
      - name: 'Validate'
        run: yarn validate

      # Unit Test
      - name: 'Unit test'
        run: yarn test

      # Upload code coverage data
      # - name: 'Upload code coverage to Codecov.io'
        # uses: codecov/codecov-action@v1
        # with:
          # token: ${{ secrets.CODECOV_TOKEN }}